import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('private documentary archive: multi-page capture, tags, expense, retrieval, archive and role isolation', async ({ page, request }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const enter = async (name: string) => {
    await page.getByRole('button', { name: new RegExp(name) }).click(); await page.getByLabel('PIN de acceso').fill('246810');
    const result = page.waitForResponse(r => r.url().endsWith('/api/login')); await page.getByRole('button', { name: 'Acceder' }).click();
    const token = (await (await result).json()).token as string; await expect(page.getByRole('button', { name: 'Abrir navegación' })).toBeVisible(); return token;
  };
  const go = async (name: string) => { await page.getByRole('button', { name: 'Abrir navegación' }).click(); await page.getByRole('dialog', { name: 'Navegación' }).getByRole('button', { name, exact: true }).click(); };
  await page.goto('/'); const token = await enter('Jefe Admin'); await go('Escáner de facturas');
  await page.getByRole('button', { name: 'Escanear y archivar' }).click();
  const upload = page.getByRole('dialog', { name: 'Incorporar documento', exact: true });
  const image = Buffer.from(await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 240; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, 160, 240); ctx.fillStyle = '#135'; ctx.fillText('FACTURA FICTICIA', 10, 20); return canvas.toDataURL('image/png').split(',')[1]; }), 'base64');
  await upload.getByLabel('Seleccionar PDF o imágenes').setInputFiles([{ name: 'pagina-1.png', mimeType: 'image/png', buffer: image }, { name: 'pagina-2.png', mimeType: 'image/png', buffer: image }]);
  await upload.getByRole('button', { name: 'Subir página 2' }).click();
  await upload.getByLabel('Título', { exact: true }).fill('Factura demo multipágina');
  await upload.getByRole('combobox', { name: 'Local', exact: true }).selectOption('Principal');
  await upload.getByRole('button', { name: '+ pendiente de pago', exact: true }).click();
  await upload.getByLabel('Notas', { exact: true }).fill('Documento sintético para demostración.');
  const posted = page.waitForResponse(r => r.url().endsWith('/api/documentos') && r.request().method() === 'POST');
  await upload.getByRole('button', { name: 'Guardar en Documentos', exact: true }).click();
  const receipt = await posted; expect(receipt.status()).toBe(201); const id = (await receipt.json()).id as number;
  await expect(upload).toHaveCount(0); await go('Documentos');
  await page.getByRole('button', { name: 'Abrir Factura demo multipágina', exact: true }).click();
  let detail = page.getByRole('dialog', { name: 'Ficha del documento' });
  await expect(detail.getByRole('link', { name: 'Descargar original' })).toBeVisible();
  await expect(detail.getByText('Página 1 de 2', { exact: true })).toBeVisible();
  await expect(detail.getByRole('button', { name: 'Página siguiente', exact: true })).toBeEnabled();
  await detail.getByRole('button', { name: 'Página siguiente', exact: true }).click();
  await expect(detail.getByText('Página 2 de 2', { exact: true })).toBeVisible();
  await expect(detail.getByRole('button', { name: 'Página anterior', exact: true })).toBeEnabled();
  await expect(detail.getByRole('button', { name: 'Página siguiente', exact: true })).toBeFocused();
  await expect(detail.getByRole('button', { name: 'Página siguiente', exact: true })).toBeDisabled();
  await expect(detail.getByRole('img', { name: 'Página 2 de Factura demo multipágina', exact: true })).toBeVisible();
  const stored = await request.get(`http://127.0.0.1:3101/api/documentos/${id}/archivo`, { headers: { Authorization: `Bearer ${token}` } });
  expect(stored.status()).toBe(200); expect((await stored.body()).toString('latin1')).toMatch(/\/Count 2\b/);
  expect((await request.get(`http://127.0.0.1:3101/api/documentos/${id}/archivo`)).status()).toBe(401);
  const downloaded = page.waitForEvent('download'); await detail.getByRole('link', { name: 'Descargar original' }).click(); expect((await downloaded).suggestedFilename()).toBe('documento-multipagina.pdf');
  await detail.getByRole('button', { name: 'Gasto vinculado', exact: true }).click();
  await detail.getByLabel('Nombre del proveedor', { exact: true }).fill('Proveedor sintético'); await detail.getByLabel('Importe total (€)').fill('42.50');
  page.once('dialog', d => d.accept()); await detail.getByRole('button', { name: 'Crear y vincular gasto' }).click();
  await expect(detail.getByText('Revisión 2', { exact: false })).toBeVisible();
  await detail.getByRole('button', { name: 'Gasto vinculado', exact: true }).click(); await expect(detail.getByRole('link', { name: 'Ver gasto', exact: true })).toBeVisible();
  const entry = await (await request.get(`http://127.0.0.1:3101/api/documentos/${id}`, { headers: { Authorization: `Bearer ${token}` } })).json(); expect(entry.gasto_id).toBeGreaterThan(0);
  await detail.getByRole('link', { name: 'Ver gasto' }).click(); await expect(page.getByRole('heading', { name: new RegExp(`Gasto n.º ${entry.gasto_id}`) })).toBeVisible();
  await page.getByRole('link', { name: `Ver justificantes del gasto ${entry.gasto_id}` }).click(); await expect(page.getByText(`Justificantes del gasto n.º ${entry.gasto_id}`, { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Abrir Factura demo multipágina' }).click(); detail = page.getByRole('dialog', { name: 'Ficha del documento' });
  await detail.getByRole('button', { name: 'Clasificación', exact: true }).click(); await detail.getByLabel('Título', { exact: true }).fill('Factura clasificada');
  await detail.getByLabel('Ocultar de la vista activa', { exact: false }).check(); await detail.getByRole('button', { name: 'Guardar clasificación' }).click();
  await expect(detail.getByRole('heading', { name: 'Factura clasificada', exact: true })).toBeVisible(); await detail.getByRole('button', { name: 'Historial', exact: true }).click();
  await expect(detail.getByText('Documento incorporado', { exact: true })).toBeVisible(); await expect(detail.getByText(new RegExp(`Creado y vinculado gasto n.º ${entry.gasto_id}`))).toBeVisible();
  await detail.getByRole('button', { name: 'Cerrar ficha' }).click(); await page.getByRole('button', { name: 'Limpiar', exact: true }).click();
  await expect(page.getByText('No hay documentos en esta selección')).toBeVisible();
  await page.getByText('Más filtros: fechas, proveedor, etiquetas y archivo', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Estado', exact: true }).selectOption('archivados'); await page.getByLabel('Etiqueta exacta').fill('pendiente de pago'); await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByRole('button', { name: 'Abrir Factura clasificada' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('documents-mobile.png'), fullPage: true });
  await page.reload(); await enter('Encargado Principal'); // persisted after a fresh authenticated session
  await page.getByText('Más filtros: fechas, proveedor, etiquetas y archivo', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Estado', exact: true }).selectOption('archivados'); await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByRole('button', { name: 'Abrir Factura clasificada' })).toBeVisible();
  await page.getByRole('button', { name: 'Abrir Factura clasificada' }).click(); detail = page.getByRole('dialog', { name: 'Ficha del documento' });
  await expect(detail.getByRole('link', { name: 'Descargar original' })).toBeVisible();
  await detail.getByRole('button', { name: 'Clasificación', exact: true }).click(); await detail.getByLabel('Ocultar de la vista activa', { exact: false }).uncheck(); await detail.getByRole('button', { name: 'Guardar clasificación' }).click();
  await expect(detail.getByText('Revisión 4', { exact: false })).toBeVisible(); await detail.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.reload(); await enter('María García'); await expect(page.getByRole('heading', { name: 'Documentos', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Abrir navegación' }).click(); await expect(page.getByRole('dialog', { name: 'Navegación' }).getByRole('button', { name: 'Documentos', exact: true })).toHaveCount(0);
});

test('document review: narrow-screen image zoom, protected drafts, confirmed save with failed refresh and URL filters', async ({ page, request }) => {
  await page.setViewportSize({ width: 320, height: 740 });
  await page.goto('/'); await page.getByRole('button', { name: /Jefe Admin/ }).click(); await page.getByLabel('PIN de acceso').fill('246810');
  const login = page.waitForResponse(r => r.url().endsWith('/api/login')); await page.getByRole('button', { name: 'Acceder' }).click();
  const token = (await (await login).json()).token as string;
  const base64 = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 1000; canvas.height = 1400; const ctx = canvas.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 1000, 1400); ctx.fillStyle = 'black'; ctx.font = '40px sans-serif'; ctx.fillText('REVISIÓN SINTÉTICA', 40, 100); return canvas.toDataURL('image/png').split(',')[1]; });
  const created = await request.post('http://127.0.0.1:3101/api/documentos', { headers: { Authorization: `Bearer ${token}`, 'Idempotency-Key': randomUUID() }, data: { local: 'Principal', titulo: 'Justificante de revisión', fecha: '2026-09-20', tipo: 'ticket', etiquetas: [], notas: '', proveedor_id: null, archivo: { nombre: 'revision.png', mime: 'image/png', base64 } } });
  expect(created.status()).toBe(201); const id = (await created.json()).id as number;
  await page.getByRole('button', { name: 'Abrir navegación' }).click(); await page.getByRole('dialog', { name: 'Navegación' }).getByRole('button', { name: 'Documentos', exact: true }).click();
  await page.getByRole('button', { name: 'Limpiar', exact: true }).click(); await page.getByRole('button', { name: 'Abrir Justificante de revisión', exact: true }).click();
  const detail = page.getByRole('dialog', { name: 'Ficha del documento' });
  await detail.getByRole('button', { name: 'Ampliar imagen' }).click();
  const imageRegion = detail.getByRole('region', { name: 'Vista de Justificante de revisión' });
  expect(await imageRegion.evaluate(el => el.scrollWidth > el.clientWidth)).toBe(true);
  expect(await detail.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await imageRegion.focus(); await page.keyboard.press('ArrowRight');
  await detail.getByRole('button', { name: 'Clasificación', exact: true }).click(); await detail.getByLabel('Título', { exact: true }).fill('Revisión conservada');
  page.once('dialog', d => d.dismiss()); await page.keyboard.press('Escape'); await expect(detail).toBeVisible();
  await detail.getByRole('button', { name: 'Historial', exact: true }).click(); await detail.getByRole('button', { name: 'Clasificación', exact: true }).click();
  await expect(detail.getByLabel('Título', { exact: true })).toHaveValue('Revisión conservada');
  await detail.getByLabel('Nueva etiqueta').fill('revisar');
  let failRead = false; let puts = 0;
  await page.route(`**/api/documentos/${id}`, async route => {
    if (route.request().method() === 'PUT') { puts++; failRead = true; await route.continue(); }
    else if (failRead) await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Lectura interrumpida en la prueba' }) });
    else await route.continue();
  });
  await detail.getByRole('button', { name: 'Guardar clasificación' }).click();
  await expect(detail.getByRole('alert')).toContainText('Lectura interrumpida'); await expect(detail.getByRole('status')).toContainText('El servidor ha confirmado el cambio');
  failRead = false; await detail.getByRole('button', { name: 'Actualizar ficha desde el servidor' }).click();
  await expect(detail.getByLabel('Título', { exact: true })).toHaveValue('Revisión conservada'); await expect(detail.getByRole('button', { name: 'Quitar etiqueta revisar' })).toBeVisible(); expect(puts).toBe(1);
  await detail.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.getByText('Más filtros: fechas, proveedor, etiquetas y archivo', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Vínculo contable' }).selectOption('sin_gasto'); await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page).toHaveURL(/vinculo=sin_gasto/); await expect(page.getByRole('button', { name: 'Abrir Revisión conservada' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Local del archivo' }).selectOption('Segundo Local'); await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByText('No hay documentos en esta selección')).toBeVisible();
  await page.goBack(); await expect(page.getByRole('combobox', { name: 'Local del archivo' })).toHaveValue('Todos'); await expect(page.getByRole('button', { name: 'Abrir Revisión conservada' })).toBeVisible();
  for (const width of [320, 390, 1280]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); }
});
