import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { unzipSync, strFromU8 } from 'fflate';

test('review inbox and monthly package preserve originals, venue boundaries and financial data', async ({ page, request }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/'); await page.getByRole('button', { name: /Jefe Admin/ }).click(); await page.getByLabel('PIN de acceso').fill('246810');
  const login = page.waitForResponse(r => r.url().endsWith('/api/login')); await page.getByRole('button', { name: 'Acceder' }).click();
  const headers = { Authorization: `Bearer ${(await (await login).json()).token}` };
  const api = 'http://127.0.0.1:3101/api';
  const before = await (await request.get(`${api}/gastos`, { headers })).json();
  const base64 = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 300; canvas.height = 400; const ctx = canvas.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 300, 400); ctx.fillStyle = 'black'; ctx.fillText('FACTURA SINTÉTICA', 20, 30); return canvas.toDataURL('image/png').split(',')[1]; });
  const created = await request.post(`${api}/documentos`, { headers: { ...headers, 'Idempotency-Key': randomUUID() }, data: { local: 'Principal', titulo: 'Documento para gestoría', fecha: '2026-09-20', tipo: 'factura_proveedor', proveedor_id: null, etiquetas: ['gestoría'], notas: '', archivo: { nombre: 'gestoria.png', mime: 'image/png', base64 } } });
  expect(created.status()).toBe(201); const id = (await created.json()).id as number;
  await page.getByRole('button', { name: 'Abrir navegación' }).click(); await page.getByRole('dialog', { name: 'Navegación' }).getByRole('button', { name: 'Documentos', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar Documento para gestoría', exact: true }).click();
  const detail = page.getByRole('dialog', { name: 'Ficha del documento' });
  await detail.getByLabel('Responsable de revisión').selectOption('1');
  await detail.getByLabel('Fecha límite de revisión').fill('2026-09-01');
  await detail.getByRole('combobox', { name: 'Estado de revisión', exact: true }).selectOption('en_revision');
  await detail.getByLabel('Observaciones de revisión').fill('Comprobar clasificación y original.');
  await detail.getByRole('button', { name: 'Guardar revisión' }).click();
  await expect(detail.getByText('Revisión 2', { exact: false })).toBeVisible();
  await detail.getByRole('button', { name: 'Cerrar ficha' }).click();
  await page.getByText('Bandeja de revisión', { exact: false }).first().click();
  await page.getByRole('button', { name: 'Mis pendientes →', exact: true }).click();
  await expect(page).toHaveURL(/responsable=mios/);
  await page.getByRole('button', { name: 'Revisar Documento para gestoría', exact: true }).click();
  await detail.getByRole('combobox', { name: 'Estado de revisión', exact: true }).selectOption('revisado');
  page.once('dialog', d => d.accept()); await detail.getByRole('button', { name: 'Guardar revisión' }).click();
  await expect(detail.getByText('Revisión 3', { exact: false })).toBeVisible();
  await detail.getByRole('button', { name: 'Cerrar ficha' }).click();
  await expect(page.getByRole('button', { name: 'Revisar Documento para gestoría', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Paquete para gestoría', exact: true }).click();
  const pack = page.getByRole('dialog', { name: 'Paquete mensual para gestoría' });
  await pack.getByLabel('Local del paquete').selectOption('Principal'); await pack.getByLabel('Mes documental').fill('2026-09');
  await pack.getByRole('button', { name: 'Consultar selección' }).click();
  await expect(pack.getByText('Documento para gestoría', { exact: false })).toBeVisible();
  await pack.getByRole('button', { name: 'Preparar ZIP' }).click();
  const download = page.waitForEvent('download'); await pack.getByRole('link', { name: 'Descargar ZIP' }).click();
  const downloaded = await download; expect(await downloaded.failure()).toBeNull();
  const files = unzipSync(readFileSync((await downloaded.path())!)); const manifest = JSON.parse(strFromU8(files['indice.json']));
  expect(manifest.documentos).toHaveLength(1); expect(manifest.documentos[0].id).toBe(id);
  expect(Buffer.from(files[manifest.documentos[0].archivo])).toEqual(Buffer.from(base64, 'base64'));
  expect(strFromU8(files['indice.html'])).toContain('Documento para gestoría');
  for (const width of [320, 390, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await pack.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  }
  await page.screenshot({ path: testInfo.outputPath('monthly-package-desktop.png'), fullPage: true });
  await pack.getByRole('button', { name: 'Cerrar paquete' }).click();
  await page.getByRole('button', { name: 'Limpiar', exact: true }).click();
  await page.getByRole('button', { name: 'Abrir Documento para gestoría', exact: true }).click();
  await detail.getByRole('button', { name: 'Clasificación', exact: true }).click(); await detail.getByLabel('Título', { exact: true }).fill('Documento corregido');
  await detail.getByRole('button', { name: 'Guardar clasificación' }).click(); await expect(detail.getByText('Revisión 4', { exact: false })).toBeVisible();
  const record = await (await request.get(`${api}/documentos/${id}`, { headers })).json(); expect(record.revision_estado).toBe('pendiente'); expect(record.revisado_por).toBeNull();
  expect(await (await request.get(`${api}/gastos`, { headers })).json()).toEqual(before);
});
