import { test, expect } from '@playwright/test';

test('management prepares routines once, employees complete and acknowledge, history survives archive', async ({ page, request }, info) => {
  const login = await request.post('http://127.0.0.1:3101/api/login', { data: { usuario_id: 1, pin: '246810' } });
  const headers = { Authorization: `Bearer ${(await login.json()).token}` };
  for (const [id, nombre, rol, local] of [[2, 'Dora', 'manager', 'Principal'], [1, 'Felipe', 'owner', 'Todos']]) {
    expect((await request.put(`http://127.0.0.1:3101/api/usuarios/${id}`, { headers, data: { nombre, rol, local, telefono: '' } })).ok()).toBe(true);
  }
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/');
  await page.getByRole('button', { name: /Dora/ }).click(); await page.getByLabel('PIN de acceso').fill('246810'); await page.getByRole('button', { name: 'Acceder' }).click();
  await page.getByRole('link', { name: 'Relevo y rutinas', exact: true }).click();
  await page.getByLabel('Día de las rutinas').fill('2026-09-20');
  await page.getByRole('button', { name: 'Nueva rutina' }).click();
  await expect(page.getByLabel('Nombre de la rutina')).toBeFocused();
  await page.getByLabel('Nombre de la rutina').fill('Apertura de Aguacate');
  await page.getByLabel('Pasos, uno por línea').fill('Revisar mesas\nComprobar vajilla');
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Nueva rutina' }).click();
  await expect(page.getByLabel('Nombre de la rutina')).toHaveValue('Apertura de Aguacate');
  await page.getByRole('button', { name: 'Guardar rutina' }).click();
  await expect(page.getByText(/Rutina guardada/)).toBeVisible();
  await expect(page.getByText('Todavía no hay tareas de rutina preparadas para este día.')).toBeVisible();
  await page.getByRole('button', { name: 'Preparar tareas del día' }).click();
  const checklist = page.getByRole('region', { name: 'Lista de apertura' });
  await expect(checklist.getByRole('checkbox')).toHaveCount(2);
  await page.getByRole('button', { name: 'Preparar tareas del día' }).click();
  await expect(page.getByRole('button', { name: 'Preparar tareas del día' })).toBeEnabled();
  await expect(checklist.getByRole('checkbox')).toHaveCount(2);
  await page.getByRole('button', { name: 'Dejar aviso' }).click();
  await page.getByLabel('Qué debe saber el siguiente turno').fill('La mesa 4 necesita revisión antes del servicio.');
  await page.getByRole('button', { name: 'Guardar aviso' }).click();
  await expect(page.getByText('Sin lecturas confirmadas.')).toBeVisible();
  await page.getByRole('button', { name: 'Gestionar aviso', exact: true }).click();
  await page.getByRole('combobox', { name: 'Responsable', exact: true }).selectOption('3');
  await page.getByRole('combobox', { name: 'Prioridad del aviso', exact: true }).selectOption('alta');
  await page.getByRole('button', { name: 'Guardar gestión' }).click();
  await expect(page.locator('article > p').filter({ hasText: 'Pendiente · Prioridad alta · María García' })).toBeVisible();
  await page.getByLabel('Local de la jornada').selectOption('Segundo Local');
  await expect(page.getByText('No hay avisos pendientes para este local.')).toBeVisible();
  await expect(page.getByRole('checkbox', { name: /Revisar mesas/ })).toHaveCount(0);
  await page.getByLabel('Local de la jornada').selectOption('Principal');
  await expect(page.getByText('La mesa 4 necesita revisión antes del servicio.')).toBeVisible();
  await page.screenshot({ path: info.outputPath('handover-manager-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.getByRole('button', { name: /María García/ }).click(); await page.getByLabel('PIN de acceso').fill('246810'); await page.getByRole('button', { name: 'Acceder' }).click();
  await expect(page.getByRole('heading', { name: 'Relevo y rutinas', exact: true })).toBeVisible();
  await page.getByLabel('Día de las rutinas').fill('2026-09-20');
  await expect(page.getByRole('button', { name: 'Nueva rutina' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Resolver aviso' })).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Ver avisos', exact: true }).selectOption('mios');
  await page.getByRole('button', { name: 'Empezar mi gestión' }).click();
  await expect(page.locator('article > p').filter({ hasText: 'En curso · Prioridad alta · María García' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Ver avisos', exact: true }).selectOption('pendientes');
  await page.getByRole('button', { name: 'He leído el aviso' }).click();
  await expect(page.getByText('Ya has confirmado la lectura')).toBeVisible();
  await page.getByRole('checkbox', { name: /Revisar mesas/ }).click();
  await expect(page.getByRole('checkbox', { name: /Revisar mesas/ })).toBeChecked();
  await expect(checklist.getByRole('heading', { name: 'Apertura · 1/2' })).toBeVisible();
  await expect(checklist.getByText(/María García/)).toBeVisible();
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('handover-employee-320.png'), fullPage: true });
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.getByRole('button', { name: /Felipe/ }).click(); await page.getByLabel('PIN de acceso').fill('246810'); await page.getByRole('button', { name: 'Acceder' }).click();
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(page.getByRole('heading', { name: 'Relevo y rutinas', exact: true })).toBeVisible(); await page.getByLabel('Día de las rutinas').fill('2026-09-20');
  page.on('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Resolver aviso' }).click();
  await expect(page.getByText('No hay avisos pendientes para este local.')).toBeVisible();
  await page.getByLabel('Mostrar también los resueltos').check();
  await expect(page.getByText(/Resuelto por Felipe/)).toBeVisible();
  await page.getByText('Rutinas configuradas (1 activas)', { exact: true }).click();
  await page.getByRole('button', { name: 'Archivar rutina' }).click();
  await expect(page.getByText('Apertura de Aguacate · apertura · Archivada', { exact: true })).toBeVisible();
  await expect(checklist.getByRole('checkbox')).toHaveCount(2);
  await page.screenshot({ path: info.outputPath('handover-owner-desktop.png'), fullPage: true });
  expect(errors).toEqual([]);
});
